version: "3"

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=password
    networks:
      - my-app-network
    volumes:
      - mysql-database-volume:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    image: pr323088/docker-spring-boot-rest:0.0.1-SNAPSHOT
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8085:8085
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydb
      - DATABASE_PORT=3306
    networks:
      - my-app-network

# Volumes
volumes:
  mysql-database-volume:

networks:
  my-app-network: